global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'mlops-app'
    static_configs:
      - targets: ['<ML_OPS_SERVICE_IP>:8000']
